### ISSUE TITLE
URGENT - Move QR code for WeChat to another page

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#131]
The image is too big.

We should have a hyperlink on the text which goes to a page in the website with the image and a single paragraph of (localized) text above it explaining what to do.

**Comment by bobsummerwill** [comment]
The single paragraph is the "Please scan the QR code below to send a friend request and we will add you to the WeChat group".

We would remove that text from the Resources section, and make the "WeChat" bulletpoint into a hyperlink to that new page.

**Comment by gd8097019** [comment]
The project was not supports for new page. Even nav menu linked with "#overview" hashes etc. When you go the new page navigation component was broken. I changed <a> links with <vue-router>'s and added scrollBehaivour event to `router/index.js` to handle hashed properly. 

That is important because you could want to add more pages in your project. Right now you can easily add. 

Also created /wechat pages and moved data as you want. 

Check my PR: https://github.com/ETCGrantsDAO/etc-grants-dao-website/pull/161

**Comment by bobsummerwill** [comment]
Thanks!

**Comment by bobsummerwill** [comment]
I merged the changes but it still is not working for me:

Page Not Found
Looks like you've followed a broken link or entered a URL that doesn't exist on this site.

[ Back to our site](https://elegant-blini-3fea6b.netlify.app/)

**Comment by gd8097019** [comment]
Sorry for wasting time It is working in my local computer(see: video). I see the problem about netlify redirecting issue. See: https://medium.com/@ishoshot/page-not-found-on-reload-vuejs-netlify-c71716e97e6

I created new PR for this problem. Can you merge it and test again. 

Thanks. 

https://user-images.githubusercontent.com/102132498/214900377-d65ad1f4-f2b7-4068-87f8-0664d383d8c3.mov

**Comment by bobsummerwill** [comment]
Great - fixed!
https://github.com/ETCGrantsDAO/etc-grants-dao-website/pull/180
