### ISSUE TITLE
Improve the watermark

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#134]

**Comment by gd8097019** [comment]
Hi, I can pushed watermark codes. See my PR: https://github.com/ETCGrantsDAO/etc-grants-dao-website/pull/263

I can only generate small transparent png file from files that's why it looks like a bit small you can replace it with bigger one. See: `images/watermark.png`

Also I reduced opacity a bit for mobile, because watermark comes under the texts. You can modify opacity for desktop and mobile from here:
```
.md-watermark::before {
  content: " ";
  display: block;
  width: 100%;
  height: 100%;
  position: absolute;
  background-image: url("../images/watermark.png");
  background-repeat: no-repeat;
  **opacity: 0.60;**
  background-position: bottom right;
  background-origin: content-box;
  margin: 0px 0px 0px 5%;
  z-index: -1;
}

@media (max-width: 600px) {
  .md-watermark::before {
    **opacity: 0.3;**
    margin: 0px 0px 0px 30%;
  }
}
```

And you can adjust your watermark by changing `margin` value.

<img width="958" alt="Screen Shot 2023-01-31 at 15 09 31" src="https://user-images.githubusercontent.com/102132498/215756801-615faec9-9db9-4603-9d0a-4f91d6eab56c.png">
<img width="121" alt="Screen Shot 2023-01-31 at 15 09 48" src="https://user-images.githubusercontent.com/102132498/215756865-5cddc4db-2fca-4ccf-ab1b-961de23a59c8.png">

**Comment by bobsummerwill** [comment]
**Here in #250 , Andrew did a watermark with the diamond 2/3 on screen to the right like the retrospective document, but it's a bit odd looking, presumably because there is a some wide black border around everything?

If that is the case, and I don't think we want to get rid of that, right, then maybe instead we just do another watermark with the diamond to the right hand side but still onscreen?

Is it easy enough to tile that background across the whole page, rather than just including it at the top of each section?**

**Comment by bobsummerwill** [comment]
I tried using @andrewgdick's latest image here:
https://github.com/ETCGrantsDAO/etc-grants-dao-website/pull/268

**Comment by bobsummerwill** [comment]
I'll close #250 because everything is captured here.

**Comment by gd8097019** [comment]
Hi Bob, I tried a lot tweak with css but I think most beautiful looking one is current

**Comment by bobsummerwill** [comment]
Closed.  Good enough.
