### ISSUE TITLE
Post launch - more data-driving for sections

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#242]
There is still a fair amount of boilerplate for each section which only becomes apparent when adding and removing new sections.

1. Editing sections.json (all good).
3. Adding MD files for English and Chinese (all good).
3. Creating a src/Components/<Section/index.vue file which is cut-and-paste but for a few lines (this is not good).
4. Manually adding a link to the section in src/Components/NavBar/index.vue for the top nav (this is not good).
5. Adding three lines in src/Views/HomeView.vue (one import, one export, one use) (this is not good).

**Comment by gd8097019** [comment]
Hi Bob I know It is for Post Launch but I worked a bit for that. See my PR. Maybe you can merge it after post launch.



I created `GenericSection/index.vue`. It has props to read `md-file` from `section.js` and loops to section. 
By the way it solves 3 and 5 issue: 

**3- Creating a src/Components/<Section/index.vue file which is cut-and-paste but for a few lines (this is not good).**
4- Manually adding a link to the section in src/Components/NavBar/index.vue for the top nav (this is not good).
**5- Adding three lines in src/Views/HomeView.vue (one import, one export, one use) (this is not good).**

For `NavBar/index.vue` issue. I think to do make it manual is better because you could want to add section in your website but not in header.

**Comment by bobsummerwill** [comment]
Great - thanks, I have merged.
So please do create a follow-up PR to delete the unused files.

**Comment by bobsummerwill** [comment]
Removed dead files in https://github.com/ETCGrantsDAO/etc-grants-dao-website/pull/274
