### ISSUE TITLE
The same "too long" URI issue affects project owner updates

### ISSUE THREAD

**Issue by bobsummerwill** [ETCGrantsDAO/etc-grants-dao-website#323]
The same "too long URI" issue which we experienced for translations - #303 - is also problematic for project owners to update their proposals.   It is the same airtable form, I think, and has exactly the same issue for projects with long details.

Here it is actually worse than translations, because we don't have the "pencil button" alternative.

We've only hit this in a single instance so far, so can do a manual fix, but it remains as an open issue here for future iterations.

**Comment by ahmet-shamiev** [comment]
Agree, if in case for both reviewers and translators can still make edits using "pencil buttons", for the projects owners such issue may still arise due to usage of Airtable form. I have a couple of other alternative solutions, let me prepare and test a few options before I present them. Just to remember, we mitigated the usage of "pencil button" due to ability to close updating feature for project owners when needed so.

**Comment by bobsummerwill** [comment]
I am a little confused.   If I login as me (bob@etccooperative.org) as a Project Owner, I see the UPDATE button whether or not that field in the database is set for that project.   Is there something other than UPDATE ABILITY field controlling this?

**Comment by bobsummerwill** [comment]
So please fix this if you can, but it is lower priority than the others,

**Comment by bobsummerwill** [comment]
Fixed - thanks!
